spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
spring.mustache.check-template-location=false
spring.mail.host=smtp.ionos.com
spring.mail.port=587
spring.mail.username=support@api-excellence.com
spring.mail.password=2Chron7:14!!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true